### ISSUE TITLE
Is there a way to get that other fake tree-of-thoughts repo taken down?

### ISSUE THREAD

**Issue by jakderrida** [ysymyth/tree-of-thought-llm#17]
Sorry if this isn't the place to post his inquiry, but I had, at first, given up on your process while thinking this spamming troll was you guys. Obviously, it's auto-generated fake code that doesn't really work, but has a toxic effect on your reputation.
https://github.com/kyegomez/tree-of-thoughts

I feel so sickened that this fraud is willing to make so many fooled by him that didn't catch on lose faith in your research, robbing you of countless citations to your credits and potential future breakthroughs just for some github stars. Can I post a reward somewhere for whomever shuts it down or something?

**Comment by kyegomez** [comment]
it's not fake, it's an implementation. Nowhere did i say it's the original implementation of tree of thoughts. 

And, no it cannot be taken down this is open source. And i'm not robbing anybody of anything. I provided an repository when there was no code or anything.

**Comment by ysymyth** [comment]
Hi, I'll add "official implementation" into the description and link to other implementations later in readme. @kyegomez it would be nice if you can also link to ours in your repo to explain? thanks!

**Comment by Xrayez** [comment]
@jakderrida thanks for making this concern public, I was also quite confused by the "more popular" repo.

The entire description in @kyegomez's gives off weird vibes/hype, as if it's the culmination of @kyegomez's life's work.

It's important to clarify the distinction between the original research and its implementations to avoid confusion. Giving **explicit** credit and clearly stating that a repository is an implementation rather than the original research is just a good practice.

> Obviously, it's auto-generated fake code that doesn't really work

I cannot assert whether it's a fraud, but it certainly feels overly-enthusiastic.

In situations like these, it's always beneficial to provide clear and accurate information to avoid any misunderstandings or misinterpretations.

> And, no it cannot be taken down this is open source. And i'm not robbing anybody of anything.

I kindly suggest making the necessary updates in @kyegomez's repository to make the distinction more **explicit**. It's not just about a project being Open Source. Clear communication within the open-source community are equally crucial for maintaining transparency and promoting proper attribution, because these are the core principles behind Open Source.

Linking to this repository would suffice to clear this apparent confusion.

**Comment by ysymyth** [comment]
Can anyone suggest what I can do? E.g. https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice ?

**Comment by ysymyth** [comment]
Given the radically rude and unbelievable responses in https://github.com/kyegomez/tree-of-thoughts/issues/54 https://github.com/kyegomez/tree-of-thoughts/issues/55 https://github.com/kyegomez/tree-of-thoughts/issues/56 I have no choice but to report to Github for abuse and repo takedown. Stay tuned.

I explained the situation on twitter: https://twitter.com/ShunyuYao12/status/1663946702754021383 thanks if you can spread the words and clarify about the right code for ToT

**Comment by kyegomez** [comment]
Rude? You are still acting out of emotions like a monkey.

Improve the algorithm and stop talking shit.

**Comment by bjm179** [comment]
Hi Shunyu 

Sorry to see you having to deal with this. I just want to pass on my congratulations for your incredible work - you’re inspiring many people around the world, including some of us way down under.

I hope this situation with the other implementation can be resolved and it is labelled more appropriately to avoid creating such obvious confusion.

keep up the great work my friend.

**Comment by jakderrida** [comment]
> Hi, I'll add "official implementation" into the description and link to other implementations later in readme. @kyegomez it would be nice if you can also link to ours in your repo to explain? thanks!

Thank you so much. I know the paper should have been sufficient. However, I suppose I got overly excited to think it was done early and that was followed by abject disappointment, followed by a notification from Reddit mods that the other one wasn't by the researcher. Don't get me wrong. I was certainly excited to try it again, as was everyone I notified that the repo I posted was not the one from the paper. It really is an incredibly novel solution that I've found numerous uses for already.
Much appreciation,
Tom

**Comment by dbruns** [comment]
It is only a "real issue" because people like you give it attention. Your
attention is valuable and one way you can resolve the problem is to stop
paying any of your valuable attention to things that you cannot control. I
do understand your concern and can empathize, but it is important to
acknowledge that there are a diverse set of people with a diverse set of
beliefs and the best you can do is challenge others without trying to
impress your beliefs upon them. It seems as though this has been done
already, and there are more meaningful ways to spend your attention.

**Comment by jakderrida** [comment]
Well, I only regret bringing it up because I failed to consider that the maker of this repo might reach out to the other "coder" not realizing he's a troll that would definitely respond as trolls do. As for bringing it up at all; it was a genuine inquiry regarding what can be done about someone that obviously auto-generated crap that was embarrassingly and obviously intended to mislead others into thinking it was by the actual hard-working researchers. Why do I think that's a problem? Good question. It hurts their reputation and jeopardizes the ability for their work to get what I believe is proper credit. It's one thing if the other repo was of the same quality as this one and posted free of any ill intent. However, that's definitely not the case. Also, to another comment saying they can't speak to whether it was autogenerated, please go to the first rendition of their repo and ask yourself if human-made code is typically filled with fake repos that literally don't exist. That's something only generative AI does. Usually because the package exists in another language and it just hallucinates that it exists with the one you're using.
